services:
  mongo:
    image: mongo:8
    ports: ["${MONGO_PORT}:${MONGO_PORT}"]
    volumes:
      - mongo_data:/data/db
    networks: [tech-net]

  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: tech-challenge-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [tech-net]

  history-service:
    build: .
    depends_on: [mongo, rabbitmq]
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      SPRING_RABBITMQ_HOST: tech-challenge-rabbit
      SPRING_RABBITMQ_USERNAME: ${RABBIT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBIT_PASSWORD}
      SPRING_RABBITMQ_PORT: ${RABBIT_PORT}
      AUTH_CLIENT_BASE_URL: ${AUTH_CLIENT_BASE_URL}
      AUTH_CLIENT_PATH: ${AUTH_CLIENT_PATH}
      AUTH_CLIENT_TIMEOUT: ${AUTH_CLIENT_TIMEOUT}
    ports:
      - "8085:8085"
    networks: [ tech-net ]

volumes:
  mongo_data:

networks:
  tech-net:
    external: true
