spring:
  application:
    name: appointment-history-service
  data:
    mongodb:
      uri: ${MONGO_URI}
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    listener:
      simple:
        acknowledge-mode: AUTO
        default-requeue-rejected: false
      retry:
        enabled: true
        max-attempts: 2
        initial-interval: 500ms
        multiplier: 2.0
        max-interval: 5s
  jackson:
    time-zone: UTC
    deserialization:
      adjust-dates-to-context-time-zone: false
  graphql:
    graphiql:
      enabled: true
    schema:
      introspection:
        enabled: true
      printer:
        enabled: true
server:
  port: 8085

auth:
  client:
    base-url: ${AUTH_CLIENT_BASE_URL}
    path: ${AUTH_CLIENT_PATH}
    timeout-millis: ${AUTH_CLIENT_TIMEOUT}

---
spring:
  config.activate.on-profile: docker
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}